before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gyp
language: cpp
script: 
        - gyp ./test/mgtest.gyp --depth=. -Duv_library=static_library "-Dtarget_arch=x64" -I./deps/libuv/common.gypi
        - make
        - env srcdir="$(pwd)/test" out/Release/mgtest
