sudo: required
dist: precise
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
          env: COMPILER=g++-5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gyp 
script: 
        - git clone https://chromium.googlesource.com/external/gyp.git gyp
        - cd test
        - python ../gyp/gyp_main.py mgtest.gyp --depth=. -Duv_library=static_library "-Dtarget_arch=x64" -I../deps/libuv/common.gypi
        - make CXX=/usr/bin/g++-5 CXX.host=/usr/bin/g++-5 CXX.target=/usr/bin/g++-5
        - env srcdir="$(pwd)" out/Release/mgtest
