language: cpp
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gyp gcc-4.8
script: 
        - cd test
        - gyp mgtest.gyp --depth=. -Duv_library=static_library "-Dtarget_arch=x64" -I../deps/libuv/common.gypi
        - make
        - env srcdir="$(pwd)" out/Release/mgtest
